version: "3.7"

services:
  jenkins:
    build:
      context: .
      args:
        USER_GROUP_ID: $USER_GROUP_ID
        USER_ID: $USER_ID
    environment:
      CASC_JENKINS_CONFIG: $REF/casc_configs/jenkins.yml
    ports:
      - 9080:8080
    volumes:
      - $HOME/data/jenkins:$JENKINS_HOME
      - ./bashrc:$JENKINS_HOME/.bashrc
      - ./jenkins.yml:$REF/casc_configs/jenkins.yml